name: Sign

on:
  push:
    branches: 
      - main
        
  pull_request:
    branches: 
      - main
  schedule:
    - cron: 0 18 * * *

jobs:
  run-it:
    runs-on: ubuntu-latest
    name: Sign_Github-Actions
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: PHP-Install
        uses: peng4740/gh-action-php@5.6

 
